export const gallery = [
    { img: "gallery/arenera-con-camion.jpeg", alt: "Camión de carga dentro de la arenera" },
    { img: "gallery/arenera-diagonal.jpeg", alt: "Arenera vista en diagonal" },
    { img: "gallery/camion-en-arenera.jpeg", alt: "Camión de carga desde atrás entrando en la arenera" },
    { img: "gallery/carga-de-camion.jpeg", alt: "Zoom in de camión siendo cargado de arena" },
    { img: "gallery/delatarena-en-puerto.jpeg", alt: "Embarcación Deltarena anclada en el puerto" },
    { img: "gallery/deltarena-de-frente.jpeg", alt: "Vista de embarcación Deltarena de frente" },
    { img: "gallery/deltarena-en-rio.jpeg", alt: "Embarcación Deltarena en el río" },
    { img: "gallery/deltarena-panoramica.jpeg", alt: "Panoramica de la embarcación Deltarena" },
    { img: "gallery/retroexcavadora.jpeg", alt: "Vista completa de una retroexcavadora" },
    { img: "gallery/retroexcavadora-panoramica.jpeg", alt: "Panoramica de una retroexcavadora" },
    { img: "gallery/rosinni-panoramica.jpeg", alt: "Panoramica de la embarcación Rossini" },
    { img: "gallery/vista-de-carga-de-camion.jpeg", alt: "Vista de atrás de camión cargando arena" },
    { img: "gallery/vista-atras-carga-camion.jpeg", alt: "Vista de atrás de camión cargando arena" },
    { img: "gallery/camion-entrando-en-arenera.jpeg", alt: "Camión de carga entrando en la arenera" },
    { img: "gallery/deltarena-recogiendo-arena.jpeg", alt: "Embarcación Deltarena recogiendo arena" },
    { img: "gallery/deltarena-calle.jpeg", alt: "Deltarena visto desde la calle" },
    { img: "gallery/arenera-de-lado.jpeg", alt: "Arenera vista desde el lado" },
]